# Generated by Django 4.1.1 on 2022-10-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descriacao',
            new_name='descricao',
        ),
    ]
