# Generated by Django 4.1.1 on 2022-10-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_descriacao_contato_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
