# Generated by Django 4.1.1 on 2022-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_alter_contato_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, default=2, max_length=255),
            preserve_default=False,
        ),
    ]
